// Write the UK venue extraction report from the artifacts the run produced,
// never from figures typed in by hand: a count in prose rots the moment the
// pack behind it is rebuilt, and this report exists to be cited.
//
// Reads data/osm/uk/venue_chunks.json and venue_counts.json plus each pack's own
// size, and writes docs/data/uk-osm-extract-<run date>.md.
//
// Run: node scripts/report_uk_venue_extract.mjs

import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { UK_VENUE_GROUPS, UK_VENUE_TAXONOMY } from "./lib/ukOsmVenueSeed.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const UK_DIR = path.join(ROOT, "data", "osm", "uk");

function formatMb(bytes) {
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

async function sizeOf(filePath) {
  try {
    return (await stat(filePath)).size;
  } catch {
    return 0;
  }
}

async function main() {
  const manifest = JSON.parse(await readFile(path.join(UK_DIR, "venue_chunks.json"), "utf8"));
  const counts = JSON.parse(await readFile(path.join(UK_DIR, "venue_counts.json"), "utf8"));

  const runDate = String(manifest.generatedAt ?? "").slice(0, 10) || "unknown";
  const outPath = path.join(ROOT, "docs", "data", `uk-osm-extract-${runDate}.md`);

  const packSizes = [];
  let packBytes = 0;
  for (const group of UK_VENUE_GROUPS) {
    const bytes = await sizeOf(path.join(UK_DIR, `uk_osm_venues_${group}.json`));
    packBytes += bytes;
    const groupRow = (counts.groups ?? []).find((row) => row.group === group);
    packSizes.push({ group, bytes, venues: groupRow?.venues ?? 0 });
  }

  const kinds = [...new Set(Object.keys(counts.uk?.byKind ?? {}))].sort();
  const kindRows = kinds.map(
    (kind) =>
      `| ${kind} | ${counts.london?.byKind?.[kind] ?? 0} | ${counts.uk?.byKind?.[kind] ?? 0} |`,
  );

  const taxonomyRows = UK_VENUE_TAXONOMY.map(
    (row) =>
      `| \`${row.key}\` | ${row.kind} | ${counts.london?.byTaxonomyKey?.[row.key] ?? 0} | ` +
      `${counts.uk?.byTaxonomyKey?.[row.key] ?? 0} | ${row.note} |`,
  );

  const stats = Array.isArray(manifest.chunkStats) ? manifest.chunkStats : [];
  const failures = Array.isArray(manifest.failures) ? manifest.failures : [];
  const missing = Array.isArray(manifest.missingChunks) ? manifest.missingChunks : [];
  const empty = stats.filter((row) => row.elements === 0);
  const busiest = [...stats].sort((a, b) => b.elements - a.elements).slice(0, 10);

  const lines = [
    `# UK OSM venue extraction, ${runDate}`,
    "",
    "Generated by `node scripts/report_uk_venue_extract.mjs` from the run's own",
    "artifacts (`data/osm/uk/venue_chunks.json`, `venue_counts.json`, and each",
    "pack's size on disk). Do not edit the figures by hand.",
    "",
    "## The run",
    "",
    `- Started: \`${manifest.generatedAt ?? "unknown"}\``,
    `- Finished: \`${manifest.completedAt ?? "unknown"}\``,
    `- Query scope: \`${manifest.scope ?? "all"}\` (one Overpass request per chunk)`,
    `- Grid: ${manifest.chunks} chunks of ${manifest.latStep}° × ${manifest.lonStep}° over \`${JSON.stringify(manifest.bbox)}\``,
    `- Area clip: ${manifest.areaFilter}`,
    `- Chunks read: ${manifest.chunksRead} of ${manifest.chunks}`,
    `- Chunks with at least one element: ${manifest.chunksWithData}`,
    `- Chunks that returned nothing: ${empty.length}`,
    `- Chunks that failed: ${failures.length}`,
    `- Chunks missing from the pack: ${missing.length}`,
    `- Raw elements returned: ${manifest.elements}`,
    `- Elements the taxonomy did not claim: ${manifest.unclassifiedElements}`,
    `- Elements with no name: ${manifest.unnamedElements}`,
    "",
    "An unnamed element is dropped by design: a pin with no name is not a place a",
    "reader can be sent to. An unclassified element came back from a neighbouring",
    "selector and is counted rather than silently discarded.",
    "",
    "## Counts by kind",
    "",
    "London is the Greater London bounding box",
    `\`${JSON.stringify(counts.greaterLondonBbox)}\`, used only to split a count.`,
    "It is never a claim that a venue is inside a borough.",
    "",
    "| Kind | London | UK |",
    "| --- | --- | --- |",
    ...kindRows,
    `| **total** | **${counts.london?.total ?? 0}** | **${counts.uk?.total ?? 0}** |`,
    "",
    "## Counts by taxonomy key",
    "",
    "| Key | Kind | London | UK | Taken when |",
    "| --- | --- | --- | --- | --- |",
    ...taxonomyRows,
    "",
    "## Pack sizes",
    "",
    "The decision point from the plan: raw responses stay out of git, and if the",
    "normalized packs pass 100 MiB they are reported here rather than committed",
    "blindly.",
    "",
    "| Pack | Venues | Size |",
    "| --- | --- | --- |",
    ...packSizes.map(
      (row) => `| \`uk_osm_venues_${row.group}.json\` | ${row.venues} | ${formatMb(row.bytes)} |`,
    ),
    `| **total** | **${counts.uk?.total ?? 0}** | **${formatMb(packBytes)}** |`,
    "",
    `Committed budget: 100.0 MB. ${
      packBytes > 100 * 1024 * 1024
        ? "**Over budget - do not commit without a decision on where these packs live.**"
        : "Within budget."
    }`,
    "",
    "## Busiest chunks",
    "",
    "| Chunk | bbox | Elements |",
    "| --- | --- | --- |",
    ...busiest.map((row) => `| \`${row.id}\` | \`${row.bbox.join(",")}\` | ${row.elements} |`),
    "",
    "## Failures",
    "",
    failures.length === 0
      ? "None. Every chunk answered."
      : ["| Chunk | Error |", "| --- | --- |", ...failures.map((row) => `| \`${row.id}\` | ${row.error} |`)].join(
          "\n",
        ),
    "",
    "## How to resume or re-run",
    "",
    "```bash",
    "npm run fetch:uk-venues              # resumes; a chunk already on disk is skipped",
    "npm run fetch:uk-venues -- --refresh # refetch every chunk",
    "npm run fetch:uk-venues -- --chunk=lat50.80_lon-0.70   # one cell",
    "npm run fetch:uk-venues -- --scope=work                # one lane of the taxonomy",
    "npm run fetch:uk-venues -- --from-raw # rebuild the packs with no network",
    "npm run build:london-venues           # cut the London kind-tagged shards",
    "node scripts/report_uk_venue_extract.mjs               # rewrite this file",
    "```",
    "",
    "A resume keeps whatever raw chunks are on disk under",
    "`data/osm/uk/raw_venues/` (gitignored) and refetches only what is missing or",
    "older than 48 hours. A partial pull never overwrites a whole pack.",
    "",
    "## Provenance",
    "",
    `- Source: ${manifest.source}`,
    `- Licence: ${manifest.license}`,
    `- Attribution: ${manifest.attribution}`,
    `- \`observedAt\` for every row is the run timestamp above.`,
    "",
    "Nothing in these packs is a price source. No row may reach a price band, a",
    "pin figure, a cheapest bucket or the Pint Index.",
    "",
  ];

  await mkdir(path.dirname(outPath), { recursive: true });
  await writeFile(outPath, `${lines.join("\n")}\n`);
  console.log(`wrote ${path.relative(ROOT, outPath)}`);
}

const isDirectRun = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isDirectRun) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
