// Write the UK venue extraction report from the artifacts the run produced,
// never from figures typed in by hand: a count in prose rots the moment the
// pack behind it is rebuilt, and this report exists to be cited.
//
// Reads data/osm/uk/venue_chunks.json and venue_counts.json, each pack's own
// size and data/freshness_registry.json, and writes docs/data/uk-osm-extract-<run date>.md.
//
// Run: node scripts/report_uk_venue_extract.mjs

import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { UK_VENUE_GROUPS, UK_VENUE_TAXONOMY } from "./lib/ukOsmVenueSeed.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const UK_DIR = path.join(ROOT, "data", "osm", "uk");

function formatMb(bytes) {
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

async function sizeOf(filePath) {
  try {
    return (await stat(filePath)).size;
  } catch {
    return 0;
  }
}

/** A table cell's text with its pipes and angle brackets escaped, so a note
 * such as `alcohol=yes|served` stays in its own column and `<alcoholic name>`
 * is not swallowed as an HTML tag. */
export function markdownCell(text) {
  return String(text).replaceAll("|", "\\|").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
}

async function main() {
  const manifest = JSON.parse(await readFile(path.join(UK_DIR, "venue_chunks.json"), "utf8"));
  const counts = JSON.parse(await readFile(path.join(UK_DIR, "venue_counts.json"), "utf8"));

  const runDate = String(manifest.generatedAt ?? "").slice(0, 10) || "unknown";

  const registry = JSON.parse(await readFile(path.join(ROOT, "data", "freshness_registry.json"), "utf8"));
  const registeredPacks = (registry.datasets ?? [])
    .map((dataset) => String(dataset.artifact ?? ""))
    .filter((artifact) => artifact.startsWith("data/osm/uk/uk_osm_venues_"));

  // The London publish is optional in this report: the packs can exist before
  // the shards are cut, and a report that invented a shard count would be worse
  // than one that stays quiet about it.
  let londonManifest = null;
  let londonShards = 0;
  let londonBytes = 0;
  const londonDir = path.join(ROOT, "public", "data", "london_venues");
  try {
    londonManifest = JSON.parse(await readFile(path.join(londonDir, "manifest.json"), "utf8"));
    londonShards = Array.isArray(londonManifest.shards) ? londonManifest.shards.length : 0;
    londonBytes = await sizeOf(path.join(londonDir, "manifest.json"));
    const generation = String(londonManifest.urlPrefix ?? "").split("/").filter(Boolean).pop();
    for (const shard of londonManifest.shards ?? []) {
      londonBytes += await sizeOf(path.join(londonDir, "packs", generation, `${shard.id}.json`));
    }
  } catch {
    londonManifest = null;
  }
  const outPath = path.join(ROOT, "docs", "data", `uk-osm-extract-${runDate}.md`);

  const packSizes = [];
  let packBytes = 0;
  for (const group of UK_VENUE_GROUPS) {
    const bytes = await sizeOf(path.join(UK_DIR, `uk_osm_venues_${group}.json`));
    packBytes += bytes;
    const groupRow = (counts.groups ?? []).find((row) => row.group === group);
    packSizes.push({ group, bytes, venues: groupRow?.venues ?? 0 });
  }

  const kinds = [...new Set(Object.keys(counts.uk?.byKind ?? {}))].sort();
  const kindRows = kinds.map(
    (kind) =>
      `| ${kind} | ${counts.london?.byKind?.[kind] ?? 0} | ${counts.uk?.byKind?.[kind] ?? 0} |`,
  );

  const taxonomyRows = UK_VENUE_TAXONOMY.map(
    (row) =>
      `| \`${row.key}\` | ${row.kind} | ${counts.london?.byTaxonomyKey?.[row.key] ?? 0} | ` +
      `${counts.uk?.byTaxonomyKey?.[row.key] ?? 0} | ${markdownCell(row.note)} |`,
  );

  const stats = Array.isArray(manifest.chunkStats) ? manifest.chunkStats : [];
  const failures = Array.isArray(manifest.failures) ? manifest.failures : [];
  const missing = Array.isArray(manifest.missingChunks) ? manifest.missingChunks : [];
  const empty = stats.filter((row) => row.elements === 0);
  const busiest = [...stats].sort((a, b) => b.elements - a.elements).slice(0, 10);

  const lines = [
    `# UK OSM venue extraction, ${runDate}`,
    "",
    "Generated by `node scripts/report_uk_venue_extract.mjs` from the run's own",
    "artifacts (`data/osm/uk/venue_chunks.json`, `venue_counts.json`, and each",
    "pack's size on disk). Do not edit the figures by hand.",
    "",
    "## The run",
    "",
    `- Started: \`${manifest.generatedAt ?? "unknown"}\``,
    `- Finished: \`${manifest.completedAt ?? "unknown"}\``,
    `- Query scope: \`${manifest.scope ?? "all"}\` (one Overpass request per chunk)`,
    `- Grid: ${manifest.chunks} chunks of ${manifest.latStep}° × ${manifest.lonStep}° over \`${JSON.stringify(manifest.bbox)}\``,
    `- Area clip: ${manifest.areaFilter}`,
    `- Chunks read: ${manifest.chunksRead} of ${manifest.chunks}`,
    `- Chunks with at least one element: ${manifest.chunksWithData}`,
    `- Chunks that returned nothing: ${empty.length}`,
    `- Chunks that failed: ${failures.length}`,
    `- Chunks missing from the pack: ${missing.length}`,
    `- Raw elements returned: ${manifest.elements}`,
    `- Elements the taxonomy did not claim: ${manifest.unclassifiedElements}`,
    `- Elements with no name: ${manifest.unnamedElements}`,
    "",
    "An unnamed element is dropped by design: a pin with no name is not a place a",
    "reader can be sent to. An unclassified element came back from a neighbouring",
    "selector and is counted rather than silently discarded.",
    "",
    "## Counts by kind",
    "",
    "London is the Greater London bounding box",
    `\`${JSON.stringify(counts.greaterLondonBbox)}\`, used only to split a count.`,
    "It is never a claim that a venue is inside a borough.",
    "",
    "| Kind | London | UK |",
    "| --- | --- | --- |",
    ...kindRows,
    `| **total** | **${counts.london?.total ?? 0}** | **${counts.uk?.total ?? 0}** |`,
    "",
    "## Counts by taxonomy key",
    "",
    "| Key | Kind | London | UK | Taken when |",
    "| --- | --- | --- | --- | --- |",
    ...taxonomyRows,
    "",
    "## Pack sizes",
    "",
    "The decision point from the plan: raw responses stay out of git, and if the",
    "normalized packs pass 100 MiB they are reported here rather than committed",
    "blindly.",
    "",
    "| Pack | Venues | Size |",
    "| --- | --- | --- |",
    ...packSizes.map(
      (row) => `| \`uk_osm_venues_${row.group}.json\` | ${row.venues} | ${formatMb(row.bytes)} |`,
    ),
    `| **total** | **${counts.uk?.total ?? 0}** | **${formatMb(packBytes)}** |`,
    "",
    `Committed budget: 100.0 MB. ${
      packBytes > 100 * 1024 * 1024
        ? "**Over budget - do not commit without a decision on where these packs live.**"
        : "Within budget."
    }`,
    "",
    ...(londonManifest
      ? [
          "## The London publish",
          "",
          `\`public/data/london_venues/\`, cut by \`npm run build:london-venues\`. ${londonShards} shards`,
          `on a ${londonManifest.grid?.latStep}° × ${londonManifest.grid?.lonStep}° grid, ${formatMb(londonBytes)} in total.`,
          "",
          "That grid is FINER than the pub layer's 0.25°, because the same cell that",
          "holds a few hundred pubs holds a few thousand pubs-plus-cafes-plus-libraries",
          "and came to 278 KB against a 150 KB per-viewport budget. The budget is a",
          "promise about one fetch, so the grid is what gives.",
          "",
          "| Kind | Shipped |",
          "| --- | --- |",
          ...Object.entries(londonManifest.countsByKind ?? {})
            .sort()
            .map(([kind, n]) => `| ${kind} | ${n} |`),
          "",
          "No UI fetches these shards. The app reads two siblings cut from the same",
          "UK packs: the map (`components/PubMap.tsx`) streams `public/data/uk_base/`",
          "(`npm run build:uk-base`) through `lib/ukBasePubs.ts`, with",
          "`lib/venueKindFilters.ts` deciding which kinds it shows, and Near Desk",
          "(`components/nearme/NearDeskNow.tsx`) reads `public/data/london_desks/`",
          "(`npm run build:london-desks`) through `lib/nearDeskVenues.ts`. The shards",
          "themselves are read by `scripts/verify_london_places.mjs`,",
          "`scripts/verify_pub_hours.mjs` and the coffee pilot check in",
          "`scripts/lib/coffeePilotRows.mjs`. `lib/londonVenueShards.ts` is the",
          "decoder and `isPubVenueKind` answers false for every non-pub kind in it, so",
          "nothing here can reach a price band, a pin figure, a cheapest bucket or the",
          "Pint Index.",
          "",
        ]
      : []),
    "## Freshness",
    "",
    registeredPacks.length === 0
      ? [
          "These packs carry no entry in `data/freshness_registry.json`, so the",
          "freshness spine cannot report them stale or unmeasurable. Wiring them in is",
          "its own change, because it moves file tracing and audit behaviour with it.",
        ].join("\n")
      : `\`data/freshness_registry.json\` tracks ${registeredPacks
          .map((artifact) => `\`${artifact}\``)
          .join(", ")}.`,
    "",
    "## Busiest chunks",
    "",
    "| Chunk | bbox | Elements |",
    "| --- | --- | --- |",
    ...busiest.map((row) => `| \`${row.id}\` | \`${row.bbox.join(",")}\` | ${row.elements} |`),
    "",
    "## Failures",
    "",
    failures.length === 0
      ? "None. Every chunk answered."
      : ["| Chunk | Error |", "| --- | --- |", ...failures.map((row) => `| \`${row.id}\` | ${row.error} |`)].join(
          "\n",
        ),
    "",
    "## How to resume or re-run",
    "",
    "```bash",
    "npm run fetch:uk-venues              # resumes; a chunk already on disk is skipped",
    "npm run fetch:uk-venues -- --refresh # refetch every chunk",
    "npm run fetch:uk-venues -- --chunk=lat50.80_lon-0.70   # one cell",
    "npm run fetch:uk-venues -- --scope=work                # one lane of the taxonomy",
    "npm run fetch:uk-venues -- --from-raw # rebuild the packs with no network",
    "npm run build:london-venues           # cut the London kind-tagged shards",
    "node scripts/report_uk_venue_extract.mjs               # rewrite this file",
    "```",
    "",
    "A resume keeps whatever raw chunks are on disk under",
    "`data/osm/uk/raw_venues/` (gitignored) and refetches only what is missing or",
    "older than 48 hours. A partial pull never overwrites a whole pack.",
    "",
    "`--from-raw` asks Overpass nothing, so the packs it writes carry the oldest",
    "OSM snapshot timestamp among the raws they were rebuilt from, and no stamp at",
    "all when one of those raws cannot be dated. Only a run that really fetched",
    "stamps itself with its own start time.",
    "",
    "An artifact describes a complete run of its OWN scope. So a `--scope` lane",
    "retry rewrites that lane's pack alone, records its chunks in",
    "`data/osm/uk/venue_chunks_<scope>.json`, and leaves the other two packs, the",
    "counts file and the figures in this report exactly as they are. Rerun without",
    "`--scope` to refresh those. A run that did not read every chunk rewrites",
    "nothing.",
    "",
    "## Provenance",
    "",
    `- Source: ${manifest.source}`,
    `- Licence: ${manifest.license}`,
    `- Attribution: ${manifest.attribution}`,
    `- \`observedAt\` for every row is the run timestamp above.`,
    "",
    "Nothing in these packs is a price source. No row may reach a price band, a",
    "pin figure, a cheapest bucket or the Pint Index.",
    "",
  ];

  await mkdir(path.dirname(outPath), { recursive: true });
  await writeFile(outPath, `${lines.join("\n")}\n`);
  console.log(`wrote ${path.relative(ROOT, outPath)}`);
}

const isDirectRun = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isDirectRun) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
