// Single write-path seam for community "Pint Drops".
//
// Two storage backends behind one API: when Supabase env is present we persist
// to the `visit_reports` table + Storage (lib/pintDropsStore); otherwise we use
// the in-memory store in lib/pintDrops.ts (process memory, resets on restart —
// fine for the prototype). Validation/provenance/rate-limit are shared and run
// before either backend. When Supabase is configured it is the source of truth:
// backend failures return a 503 instead of acknowledging data that would only
// live in process memory.

import {
  validatePintDrop,
  isRateLimited,
  addPintDrop,
  listAllVisiblePintDrops,
  listVisiblePintDrops,
  reportPintDrop,
} from "@/lib/pintDrops";
import {
  persistDrop,
  listAllVisibleDropsRemote,
  listVisibleDropsRemote,
  setDropStatusRemote,
  uploadPhoto,
  deletePhotos,
  toDTO,
  type PersistableDrop,
} from "@/lib/pintDropsStore";
import { isSupabaseConfigured, requiresSupabaseStore } from "@/lib/supabase";

const STORAGE_UNCONFIGURED_ERROR =
  "Pint Drop production storage is not configured.";

function productionStorageUnavailable(): Response | null {
  return requiresSupabaseStore() && !isSupabaseConfigured()
    ? Response.json({ error: STORAGE_UNCONFIGURED_ERROR }, { status: 503 })
    : null;
}

type Photos = { pint: File | null; venue: File | null };

// Parse either a JSON body or a multipart form. For multipart we pull the text
// fields into a plain object (validatePintDrop cleans them) and keep the photo
// Files aside. JSON bodies carry no photos. Returns null on a malformed body.
async function parseBody(
  request: Request,
): Promise<{ fields: Record<string, unknown>; photos: Photos } | null> {
  const type = request.headers.get("content-type") ?? "";
  if (type.includes("multipart/form-data")) {
    const form = await request.formData();
    const fields: Record<string, unknown> = {};
    const photos: Photos = { pint: null, venue: null };
    for (const [k, v] of form.entries()) {
      if (k === "pint_photo" && v instanceof File && v.size > 0) photos.pint = v;
      else if (k === "venue_photo" && v instanceof File && v.size > 0) photos.venue = v;
      else if (typeof v === "string") fields[k] = v;
    }
    return { fields, photos };
  }
  try {
    return {
      fields: (await request.json()) as Record<string, unknown>,
      photos: { pint: null, venue: null },
    };
  } catch {
    return null;
  }
}

export async function POST(request: Request): Promise<Response> {
  const parsed = await parseBody(request);
  if (!parsed) {
    return Response.json({ error: "Malformed request body." }, { status: 400 });
  }
  const { fields, photos } = parsed;

  // Moderation: a report hides the drop pending review.
  if (fields.action === "report") {
    const id = fields.id;
    if (typeof id !== "string") {
      return Response.json({ error: "Pint Drop not found." }, { status: 404 });
    }
    const unavailable = productionStorageUnavailable();
    if (unavailable) return unavailable;
    if (isSupabaseConfigured()) {
      try {
        const ok = await setDropStatusRemote(id, "hidden");
        return ok
          ? Response.json({ ok: true }, { status: 200 })
          : Response.json({ error: "Pint Drop not found." }, { status: 404 });
      } catch {
        return Response.json({ error: "Pint Drop storage is unavailable." }, { status: 503 });
      }
    }
    return reportPintDrop(id)
      ? Response.json({ ok: true }, { status: 200 })
      : Response.json({ error: "Pint Drop not found." }, { status: 404 });
  }

  const result = validatePintDrop(fields);
  if (!result.ok) {
    return Response.json({ error: result.error }, { status: 400 });
  }

  if (isRateLimited(result.value.handle)) {
    return Response.json({ error: "Too many submissions, slow down." }, { status: 429 });
  }

  const unavailable = productionStorageUnavailable();
  if (unavailable) return unavailable;

  if (isSupabaseConfigured()) {
    const drop: PersistableDrop = { ...result.value };
    const { venueId, id } = drop; // id is generated by validatePintDrop, so keys exist before upload
    const uploaded: string[] = [];
    try {
      // Upload both photos (if present) BEFORE the insert. On a bad file we
      // throw before persisting; on an insert failure we delete what we uploaded.
      if (photos.pint) {
        drop.pintPhotoKey = await uploadPhoto("pint", venueId, id, photos.pint);
        uploaded.push(drop.pintPhotoKey);
      }
      if (photos.venue) {
        drop.venuePhotoKey = await uploadPhoto("venue", venueId, id, photos.venue);
        uploaded.push(drop.venuePhotoKey);
      }
    } catch (err) {
      // An invalid-photo error is the user's fault — surface as 400. Anything
      // uploaded before the bad file still gets cleaned up (no orphan).
      await deletePhotos(uploaded);
      if (err instanceof Error && err.message.startsWith("Photo must")) {
        return Response.json({ error: err.message }, { status: 400 });
      }
      return Response.json({ error: "Pint Drop storage is unavailable." }, { status: 503 });
    }
    try {
      await persistDrop(drop);
    } catch {
      // Insert failed after upload — remove the now-orphaned objects, best-effort.
      await deletePhotos(uploaded);
      return Response.json({ error: "Pint Drop storage is unavailable." }, { status: 503 });
    }
    return Response.json({ drop: toDTO(drop) }, { status: 201 });
  }

  // Fallback path: in-memory store. Photos are ignored here (no Storage).
  addPintDrop(result.value);
  return Response.json({ drop: toDTO(result.value) }, { status: 201 });
}

export async function GET(request: Request): Promise<Response> {
  const venueId = new URL(request.url).searchParams.get("venueId");
  const unavailable = productionStorageUnavailable();
  if (unavailable) return unavailable;
  if (isSupabaseConfigured()) {
    try {
      const rows = venueId
        ? await listVisibleDropsRemote(venueId)
        : await listAllVisibleDropsRemote();
      return Response.json({ drops: rows.map(toDTO) }, { status: 200 });
    } catch {
      return Response.json({ error: "Pint Drop storage is unavailable." }, { status: 503 });
    }
  }
  const rows = venueId ? listVisiblePintDrops(venueId) : listAllVisiblePintDrops();
  return Response.json({ drops: rows.map(toDTO) }, { status: 200 });
}
