import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import historicPubs from "@/public/data/historic_pubs.json";
import {
  LONDON_MAP_OUTLINES,
  LONDON_MAP_PINS,
  LONDON_MAP_PUB_COUNT,
  LONDON_MAP_PUB_POINTS,
  LONDON_MAP_VIEWBOX,
} from "@/components/landing/londonMapSnapshot";

// The front door's picture is a DRAWING of London, generated once at build by
// scripts/landing/build-landing-map.mjs. Three things are held here: it stays
// small enough to be the first thing a phone paints, every mark on it is a real
// place, and nobody hand-edits the generated file.

type HistoricPub = {
  name: string;
  slug?: string;
  borough?: string;
  lat?: number;
  lng?: number;
  dateLabel?: string;
  datePrecision?: string;
  sourced?: boolean;
};

const pubs = historicPubs as HistoricPub[];

const generated = readFileSync(
  join(process.cwd(), "components/landing/londonMapSnapshot.ts"),
  "utf8",
);

/** The captain's ceiling for the hero picture. */
const MAX_KB = 80;

describe("the landing's drawing of London", () => {
  it("stays under the hero picture's size ceiling", () => {
    const kb = Buffer.byteLength(generated, "utf8") / 1024;
    expect(kb).toBeLessThan(MAX_KB);
  });

  it("is generated, and says so at the top of the file", () => {
    expect(generated.startsWith("// GENERATED by scripts/landing/build-landing-map.mjs")).toBe(true);
  });

  it("draws a frame, an outline and one dot per historic pub in it", () => {
    expect(LONDON_MAP_VIEWBOX).toMatch(/^0 0 \d+ \d+$/);
    expect(LONDON_MAP_OUTLINES.startsWith("M")).toBe(true);
    // Every dot the drawing paints, plus the six the pins name, is the count
    // the caption prints, so the words and the picture cannot disagree.
    expect(LONDON_MAP_PUB_POINTS.length + LONDON_MAP_PINS.length).toBe(LONDON_MAP_PUB_COUNT);
    expect(LONDON_MAP_PUB_COUNT).toBeGreaterThan(100);
  });

  it("names only pubs the heritage dataset holds, with the dataset's own words", () => {
    expect(LONDON_MAP_PINS).toHaveLength(6);
    for (const pin of LONDON_MAP_PINS) {
      const pub = pubs.find((row) => row.slug === pin.slug);
      expect(pub, `${pin.slug} is a real historic pub`).toBeTruthy();
      expect(pin.name).toBe(pub?.name);
      // The year comes from the row, never from the picture.
      expect(pin.label).toBe(pub?.dateLabel);
      expect(pub?.sourced).toBe(true);
      expect(pub?.datePrecision).toBe("year");
    }
  });

  it("names one pub per borough, so the six are spread across the city", () => {
    const boroughs = LONDON_MAP_PINS.map(
      (pin) => pubs.find((row) => row.slug === pin.slug)?.borough,
    );
    expect(new Set(boroughs).size).toBe(LONDON_MAP_PINS.length);
  });

  it("keeps every mark inside the frame it draws", () => {
    const [, , width, height] = LONDON_MAP_VIEWBOX.split(" ").map(Number);
    for (const [x, y] of LONDON_MAP_PUB_POINTS) {
      expect(x).toBeGreaterThanOrEqual(0);
      expect(x).toBeLessThanOrEqual(width);
      expect(y).toBeGreaterThanOrEqual(0);
      expect(y).toBeLessThanOrEqual(height);
    }
    for (const pin of LONDON_MAP_PINS) {
      expect(pin.x).toBeGreaterThanOrEqual(0);
      expect(pin.x).toBeLessThanOrEqual(width);
      expect(pin.y).toBeGreaterThanOrEqual(0);
      expect(pin.y).toBeLessThanOrEqual(height);
      // A label runs away from the nearer edge, so no name is clipped.
      expect(pin.anchor).toBe(pin.x > width / 2 ? "end" : "start");
    }
  });
});
