import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import historicPubs from "@/public/data/historic_pubs.json";
import {
  LONDON_MAP_OUTLINES,
  LONDON_MAP_PINS,
  LONDON_MAP_PUB_COUNT,
  LONDON_MAP_PUB_DOT_COUNT,
  LONDON_MAP_PUB_DOTS,
  LONDON_MAP_VIEWBOX,
} from "@/components/landing/londonMapGeometry";

// The front door's picture is a DRAWING of London, generated once at build by
// scripts/landing/build-landing-map.mjs. Three things are held here: it stays
// small enough to be the first thing a phone paints, every mark on it is a real
// place, and nobody hand-edits the generated file.

type HistoricPub = {
  name: string;
  slug?: string;
  borough?: string;
  lat?: number;
  lng?: number;
  dateLabel?: string;
  datePrecision?: string;
  sourced?: boolean;
};

const pubs = historicPubs as HistoricPub[];

const generated = readFileSync(
  join(process.cwd(), "components/landing/londonMapGeometry.ts"),
  "utf8",
);

/** The captain's ceiling for the hero picture. */
const MAX_KB = 80;

describe("the landing's drawing of London", () => {
  it("stays under the hero picture's size ceiling", () => {
    const kb = Buffer.byteLength(generated, "utf8") / 1024;
    expect(kb).toBeLessThan(MAX_KB);
  });

  it("is generated, and says so at the top of the file", () => {
    expect(generated.startsWith("// GENERATED by scripts/landing/build-landing-map.mjs")).toBe(true);
  });

  it("draws a frame, an outline and one dot per historic pub in it", () => {
    expect(LONDON_MAP_VIEWBOX).toMatch(/^0 0 \d+ \d+$/);
    expect(LONDON_MAP_OUTLINES.startsWith("M")).toBe(true);
    // Every dot the drawing paints, plus the ones the pins name, is the count
    // the lede prints, so the words and the picture cannot disagree.
    expect(LONDON_MAP_PUB_DOT_COUNT + LONDON_MAP_PINS.length).toBe(LONDON_MAP_PUB_COUNT);
    expect(LONDON_MAP_PUB_COUNT).toBeGreaterThan(100);
    // ONE path for every dot, not one element each: 293 elements are 293
    // layout objects on the phone this page is trying to paint first.
    expect(LONDON_MAP_PUB_DOTS.startsWith("M")).toBe(true);
    expect(LONDON_MAP_PUB_DOTS.match(/M/g)).toHaveLength(LONDON_MAP_PUB_DOT_COUNT);
  });

  it("names only pubs the heritage dataset holds, with the dataset's own words", () => {
    // The script caps the pins at six; the separation rule decides how many the
    // data can seat without labels touching, and today that is five.
    expect(LONDON_MAP_PINS.length).toBeGreaterThanOrEqual(4);
    expect(LONDON_MAP_PINS.length).toBeLessThanOrEqual(6);
    for (const pin of LONDON_MAP_PINS) {
      const pub = pubs.find((row) => row.slug === pin.slug);
      expect(pub, `${pin.slug} is a real historic pub`).toBeTruthy();
      expect(pin.name).toBe(pub?.name);
      // The year comes from the row, never from the picture.
      expect(pin.label).toBe(pub?.dateLabel);
      expect(pub?.sourced).toBe(true);
      expect(["year", "century"]).toContain(pub?.datePrecision);
    }
  });

  it("points two labels on one line away from each other, never at each other", () => {
    for (const [index, pin] of LONDON_MAP_PINS.entries()) {
      for (const other of LONDON_MAP_PINS.slice(index + 1)) {
        if (Math.abs(pin.y - other.y) > 80) continue;
        const left = pin.x <= other.x ? pin : other;
        const right = pin.x <= other.x ? other : pin;
        expect(left.anchor, `${left.name} runs left, away from ${right.name}`).toBe("end");
        expect(right.anchor, `${right.name} runs right, away from ${left.name}`).toBe("start");
      }
    }
  });

  it("keeps the named pins far enough apart that no two labels touch", () => {
    // Four of the oldest dated pubs stand within a few hundred metres of Fleet
    // Street, so a one-per-borough rule still stacked four labels on one spot.
    // Separation is the rule now, measured on the drawing.
    for (const [index, pin] of LONDON_MAP_PINS.entries()) {
      for (const other of LONDON_MAP_PINS.slice(index + 1)) {
        expect(Math.hypot(pin.x - other.x, pin.y - other.y)).toBeGreaterThanOrEqual(150);
      }
    }
  });

  it("keeps every mark inside the frame it draws", () => {
    const [, , width, height] = LONDON_MAP_VIEWBOX.split(" ").map(Number);
    for (const [, x, y] of LONDON_MAP_PUB_DOTS.matchAll(/M(-?[\d.]+) (-?[\d.]+)/g)) {
      expect(Number(x)).toBeGreaterThanOrEqual(-10);
      expect(Number(x)).toBeLessThanOrEqual(width);
      expect(Number(y)).toBeGreaterThanOrEqual(0);
      expect(Number(y)).toBeLessThanOrEqual(height);
    }
    for (const pin of LONDON_MAP_PINS) {
      expect(pin.x).toBeGreaterThanOrEqual(0);
      expect(pin.x).toBeLessThanOrEqual(width);
      expect(pin.y).toBeGreaterThanOrEqual(0);
      expect(pin.y).toBeLessThanOrEqual(height);
      expect(["start", "end"]).toContain(pin.anchor);
    }
  });
});
